/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Aluno;
import model.dao.AlunoDAO;

/**
 *
 * @author user
 */
public class EditarAluno extends javax.swing.JInternalFrame {

    
     //Creates new form EditarAluno
     
    public EditarAluno() {
        initComponents();
        DefaultTableModel pesquisa = (DefaultTableModel) PaAlunos.getModel();
        PaAlunos.setRowSorter(new TableRowSorter(pesquisa));
        readPesquisar();
        CampoNome.setDocument(new JTextFieldLimit(30));
        CampoEnd.setDocument(new JTextFieldLimit(40));
        CampoRA.setDocument(new JTextFieldLimit(12));
        CampoRG.setDocument(new JTextFieldLimit(12));
        CampoTurma.setDocument(new JTextFieldLimit(1));
        CampoTel.setDocument(new JTextFieldLimit(17));
        CampoSerie.setDocument(new JTextFieldLimit(3));
        CampoSexo.setDocument(new JTextFieldLimit(1));
        CampoPesq.setDocument(new JTextFieldLimit(30));
    }
       

    public void readPesquisar(){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaAlunos.getModel();
        pesquisa.setNumRows(0);
        
        AlunoDAO adao = new AlunoDAO();
        
        for(Aluno a:adao.read()){
            
            pesquisa.addRow(new Object[]{
            a.getId_a(),
            a.getRa(),
            a.getRg(),
            a.getNome(),
            a.getEndereco(),
            a.getNasc(),
            a.getSexo(),
            a.getSerie(),
            a.getTurma(),
            a.getTel()
            
            //id_a, nome,sexo,ra, serie, turma, rg, nasc, End, tel
            
            });
        
            
        }
    }
           
    
        
   
        public void readPesquisarForName(String nome){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaAlunos.getModel();
        pesquisa.setNumRows(0);
        
        AlunoDAO adao = new AlunoDAO();
        
        for(Aluno a:adao.readForName(nome)){
            
            pesquisa.addRow(new Object[]{
            a.getId_a(),
            a.getRa(),
            a.getRg(),
            a.getNome(),
            a.getEndereco(),
            a.getNasc(),
            a.getSexo(),
            a.getSerie(),
            a.getTurma(),
            a.getTel()
            
            //id_a, nome,sexo,ra, serie, turma, rg, nasc, End, tel
            
            });
        
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        CampoPesq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnEA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaAlunos = new javax.swing.JTable();
        CampoSerie = new javax.swing.JTextField();
        CampoNasc = new javax.swing.JFormattedTextField();
        CampoTurma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CampoTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CampoEnd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoRA = new javax.swing.JTextField();
        CampoRG = new javax.swing.JTextField();
        CampoSexo = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setClosable(true);
        setTitle("Editar Aluno");
        setMaximumSize(new java.awt.Dimension(914, 412));

        CampoPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesqActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Aluno");

        jToggleButton1.setText("Pesquisar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnEA.setText("Editar");
        btnEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEAActionPerformed(evt);
            }
        });

        PaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RA", "RG", "Nome", "End", "Data de Nasc", "Sexo", "Serie", "Turma", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaAlunosMouseClicked(evt);
            }
        });
        PaAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaAlunosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(PaAlunos);

        try {
            CampoNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNascActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Aluno:");

        jLabel9.setText("RA:");

        jLabel3.setText("Data de Nascimento");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("RG:");

        jLabel4.setText("Endereco:");

        jLabel11.setText("Serie:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sexo:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Turma:");

        jLabel13.setText("Telefone:");

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CampoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoRA, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEA))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CampoPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnEA))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(CampoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesqActionPerformed

    private void btnEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEAActionPerformed
        
        if(PaAlunos.getSelectedRow() != -1){
        
            Aluno a = new Aluno();
            AlunoDAO dao = new AlunoDAO();
        
            a.setRa(CampoRA.getText());
            a.setRg(CampoRG.getText());
            a.setNome(CampoNome.getText());
            a.setEndereco(CampoEnd.getText());
            a.setNasc(CampoNasc.getText());
            a.setSexo(CampoSexo.getText());
            a.setSerie((CampoSerie.getText()));
            a.setTurma(CampoTurma.getText());
            a.setTel(CampoTel.getText());
            a.setId_a((int) PaAlunos.getValueAt(PaAlunos.getSelectedRow(), 0));
        
        dao.update(a);
        readPesquisar();
              }
    }//GEN-LAST:event_btnEAActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        readPesquisarForName(CampoPesq.getText());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void CampoNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNascActionPerformed

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void PaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaAlunosMouseClicked
                if(PaAlunos.getSelectedRow()!=-1){
            
            
        CampoRA.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),1).toString());
        CampoRG.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),2).toString());
        CampoNome.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),3).toString());
        CampoEnd.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),4).toString());
        CampoNasc.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),5).toString());
        CampoSexo.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),6).toString());
        CampoSerie.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),7).toString());
        CampoTurma.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),8).toString());
        CampoTel.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),9).toString());
        
        
        }
    
    }//GEN-LAST:event_PaAlunosMouseClicked

    private void PaAlunosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaAlunosKeyReleased
        if(PaAlunos.getSelectedRow()!=-1){
            
            
        CampoRA.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),1).toString());
        CampoRG.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),2).toString());
        CampoNome.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),3).toString());
        CampoEnd.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),4).toString());
        CampoNasc.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),5).toString());
        CampoSexo.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),6).toString());
        CampoSerie.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),7).toString());
        CampoTurma.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),8).toString());
        CampoTel.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),9).toString());
        
        
        }


    }//GEN-LAST:event_PaAlunosKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoEnd;
    private javax.swing.JFormattedTextField CampoNasc;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoPesq;
    private javax.swing.JTextField CampoRA;
    private javax.swing.JTextField CampoRG;
    private javax.swing.JTextField CampoSerie;
    private javax.swing.JTextField CampoSexo;
    private javax.swing.JTextField CampoTel;
    private javax.swing.JTextField CampoTurma;
    private javax.swing.JTable PaAlunos;
    private javax.swing.JButton btnEA;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
