/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javafx.scene.control.PasswordField;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;
import model.bean.Funcionario;
import model.dao.FuncionarioDAO;

/**
 *
 * @author user
 */
public class EditarFunc extends javax.swing.JInternalFrame {

    
     //Creates new form EditarAluno
     
    public EditarFunc() {
        initComponents();
        DefaultTableModel pesquisa = (DefaultTableModel) PaFunc.getModel();
        PaFunc.setRowSorter(new TableRowSorter(pesquisa));
        readPesquisar();
        
        
        CampoNome.setDocument(new JTextFieldLimit(30));
        CampoRG.setDocument(new JTextFieldLimit(12));
        CampoEnd.setDocument(new JTextFieldLimit(40));
        CampoTel.setDocument(new JTextFieldLimit(17));
        CampoLogin.setDocument(new JTextFieldLimit(12));
        CampoSenha.setDocument(new JTextFieldLimit(5));
        CampoSenhaM.setDocument(new JTextFieldLimit(5));
        
         
        PaFunc.getColumnModel().getColumn( 7 ).setMaxWidth( 0 );  
        PaFunc.getColumnModel().getColumn( 7 ).setMinWidth( 0 );  
        PaFunc.getTableHeader().getColumnModel().getColumn( 7 ).setMaxWidth( 0 );  
        PaFunc.getTableHeader().getColumnModel().getColumn( 7 ).setMinWidth( 0 );  
        
    }
       

    public void readPesquisar(){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaFunc.getModel();
        pesquisa.setNumRows(0);
        
        FuncionarioDAO fdao = new FuncionarioDAO();
        
        for(Funcionario f:fdao.readFunc()){
            
            pesquisa.addRow(new Object[]{
            f.getId_f(),
            f.getNome(),
            f.getRg(),
            f.getNasc(),
            f.getEndereco(),
            f.getTel(),
            f.getLogin(),
            f.getSenha()
            
            
            //id_a, nome,sexo,ra, serie, turma, rg, nasc, End, tel
            
            });
        
            
        }
    }
           
    
        
   
        public void readPesquisarForName(String nome){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaFunc.getModel();
        pesquisa.setNumRows(0);
        
        FuncionarioDAO fdao = new FuncionarioDAO();
        
        for(Funcionario f:fdao.readFuncForName(nome)){
            
            pesquisa.addRow(new Object[]{
            f.getId_f(),
            f.getNome(),
            f.getRg(),
            f.getNasc(),
            f.getEndereco(),
            f.getTel(),
            f.getLogin(),
            f.getSenha()
            
            
            //id_a, nome,sexo,ra, serie, turma, rg, nasc, End, tel
            
            });
        
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        CampoPesq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnEA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaFunc = new javax.swing.JTable();
        CampoLogin = new javax.swing.JTextField();
        CampoNasc = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CampoEnd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoRG = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        CampoSenhaM = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        CampoLoginM = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setClosable(true);
        setTitle("Editar Funcionario");
        setMaximumSize(new java.awt.Dimension(914, 412));

        CampoPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesqActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Func");

        jToggleButton1.setText("Pesquisar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnEA.setText("Editar");
        btnEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEAActionPerformed(evt);
            }
        });

        PaFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "RG", "Nasc", "End", "Telefone", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaFuncMouseClicked(evt);
            }
        });
        PaFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaFuncKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(PaFunc);
        if (PaFunc.getColumnModel().getColumnCount() > 0) {
            PaFunc.getColumnModel().getColumn(7).setResizable(false);
        }

        try {
            CampoNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNascActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Func:");

        jLabel3.setText("Data de Nascimento");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("RG:");

        jLabel4.setText("Endereco:");

        jLabel11.setText("Login");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Senha:");

        jLabel13.setText("Telefone:");

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Senha Master:");

        CampoSenhaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenhaMActionPerformed(evt);
            }
        });

        jLabel15.setText("Login Master");

        CampoLoginM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoLoginMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CampoPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(28, 28, 28)
                                .addComponent(CampoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(CampoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoLoginM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoSenhaM, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEA))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(btnEA)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoSenhaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoLoginM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesqActionPerformed

    private void btnEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEAActionPerformed
        
        if(PaFunc.getSelectedRow() != -1){
        
            FuncionarioDAO ffdao = new FuncionarioDAO();
            if(ffdao.checkLoginM(CampoLoginM.getText(), CampoSenhaM.getText())){
            Funcionario f = new Funcionario();
            Funcionario ff = new Funcionario();
            FuncionarioDAO fdao = new FuncionarioDAO();
            
            f.setNome(CampoNome.getText());
            f.setRg(CampoRG.getText());
            f.setNasc(CampoNasc.getText());
            f.setEndereco(CampoEnd.getText());
            f.setTel(CampoTel.getText());
            f.setLogin(CampoLogin.getText());
            f.setSenha(CampoSenha.getText());
            f.setId_f((int) PaFunc.getValueAt(PaFunc.getSelectedRow(), 0));
        
        fdao.updateFunc(f);
        readPesquisar();
              }
            else{JOptionPane.showMessageDialog(null, "Login ou Senha Master Incorreta");
            }
        }
    }//GEN-LAST:event_btnEAActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        readPesquisarForName(CampoPesq.getText());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void CampoNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNascActionPerformed

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void PaFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaFuncMouseClicked
                if(PaFunc.getSelectedRow()!=-1){
            
            
        CampoNome.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),1).toString());
        CampoRG.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),2).toString());
        CampoNasc.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),3).toString());
        CampoEnd.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),4).toString());
        CampoTel.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),5).toString());
        CampoLogin.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),6).toString());
        CampoSenha.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),7).toString());
        
        
        
        }
    
    }//GEN-LAST:event_PaFuncMouseClicked

    private void PaFuncKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaFuncKeyReleased
        if(PaFunc.getSelectedRow()!=-1){
            
            
        CampoNome.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),1).toString());
        CampoRG.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),2).toString());
        CampoNasc.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),3).toString());
        CampoEnd.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),4).toString());
        CampoTel.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),5).toString());
        CampoLogin.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),6).toString());
        CampoSenha.setText(PaFunc.getValueAt(PaFunc.getSelectedRow(),7).toString());
        
        
        }


    }//GEN-LAST:event_PaFuncKeyReleased

    private void CampoSenhaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenhaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSenhaMActionPerformed

    private void CampoLoginMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoLoginMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoLoginMActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoEnd;
    private javax.swing.JTextField CampoLogin;
    private javax.swing.JTextField CampoLoginM;
    private javax.swing.JFormattedTextField CampoNasc;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoPesq;
    private javax.swing.JTextField CampoRG;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JPasswordField CampoSenhaM;
    private javax.swing.JTextField CampoTel;
    private javax.swing.JTable PaFunc;
    private javax.swing.JButton btnEA;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

   
   
}
