/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Aluno;
import model.bean.Livros;
import model.dao.AlunoDAO;
import model.dao.LivroDAO;
import model.dao.ReservaDAO;

/**
 *
 * @author user
 */
public class FazerReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form FazerReserva
     */
    public FazerReserva() {
        initComponents();
        readPesquisar();
        readpesquisarL();
        CampoTituloP.setDocument(new JTextFieldLimit(40));
        CampoNomeP.setDocument(new JTextFieldLimit(30));
                
    }
    
    public void readpesquisarL(){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaLivros.getModel();
        pesquisa.setNumRows(0);
        
        LivroDAO ldao = new LivroDAO();
        
        for(Livros l:ldao.readLRR()){
            
            pesquisa.addRow(new Object[]{
            l.getId_l(),
            l.getTitulo(),
            l.getAutor(),
            l.getGenero(),
            l.getDisp()
            
            
            
            
            
            });
        
            
        }
    }
      
    public void readpesquisarLT(String titulo){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaLivros.getModel();
        pesquisa.setNumRows(0);
        
        LivroDAO ldao = new LivroDAO();
        
        for(Livros l:ldao.readLTRR(titulo)){
            
            pesquisa.addRow(new Object[]{
            l.getId_l(),
            l.getTitulo(),
            l.getAutor(),
            l.getGenero(),
            l.getDisp()
            
            
            
            
            
            });
        
            
        }
    }
    
      public void readPesquisar(){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaAlunos.getModel();
        pesquisa.setNumRows(0);
        
        AlunoDAO adao = new AlunoDAO();
        
        for(Aluno a:adao.read()){
            
            pesquisa.addRow(new Object[]{
            a.getId_a(),
            a.getRa(),
            a.getRg(),
            a.getNome(),
            a.getEndereco(),
            a.getNasc(),
            a.getSexo(),
            a.getSerie(),
            a.getTurma(),
            a.getTel()
            
            //id_a, nome,sexo,ra, serie, turma, rg, nasc, End, tel
            
            });
        
            
        }
    }
           
    
        
   
        public void readPesquisarForName(String nome){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaAlunos.getModel();
        pesquisa.setNumRows(0);
        
        AlunoDAO adao = new AlunoDAO();
        
        for(Aluno a:adao.readForName(nome)){
            
            pesquisa.addRow(new Object[]{
            a.getId_a(),
            a.getRa(),
            a.getRg(),
            a.getNome(),
            a.getEndereco(),
            a.getNasc(),
            a.getSexo(),
            a.getSerie(),
            a.getTurma(),
            a.getTel()
            
            //id_a, nome,sexo,ra, serie, turma, rg, nasc, End, tel
            
            });
        
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PaLivros = new javax.swing.JTable();
        CampoTituloP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        CampoNomeP = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaAlunos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        CampoTit = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoR = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        CampoE = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        CampoIDL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CampoIDA = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Fazer Reserva");

        btnFR.setText("Reservar");
        btnFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFRActionPerformed(evt);
            }
        });

        PaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Autor", "Genero", "Disponivel S(0) e N(1)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaLivrosMouseClicked(evt);
            }
        });
        PaLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaLivrosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(PaLivros);

        CampoTituloP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTituloPActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Livro");

        jToggleButton1.setText("Pesquisar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Aluno");

        CampoNomeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomePActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Pesquisar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        PaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RA", "RG", "Nome", "End", "Data de Nasc", "Sexo", "Serie", "Turma", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaAlunosMouseClicked(evt);
            }
        });
        PaAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaAlunosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(PaAlunos);

        jLabel3.setText("Titulo Selecionado");

        CampoTit.setEnabled(false);

        jLabel4.setText("Aluno Selecionado");

        CampoNome.setEnabled(false);
        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });

        jLabel5.setText("Data de Retirada");

        try {
            CampoR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoRActionPerformed(evt);
            }
        });

        jLabel6.setText("Data de Entrega");

        try {
            CampoE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEActionPerformed(evt);
            }
        });

        jLabel7.setText("ID do Titulo");

        CampoIDL.setEnabled(false);

        jLabel8.setText("ID do Aluno");

        CampoIDA.setEnabled(false);
        CampoIDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIDAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CampoIDL))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoIDA))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(CampoTit))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CampoTituloP, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(CampoNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnFR))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoTituloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoTit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoIDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoIDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnFR)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaLivrosMouseClicked
        if(PaLivros.getSelectedRow()!=-1){

            CampoTit.setText(PaLivros.getValueAt(PaLivros.getSelectedRow(),1).toString());
            CampoIDL.setText(PaLivros.getValueAt(PaLivros.getSelectedRow(),0).toString());

        }
    }//GEN-LAST:event_PaLivrosMouseClicked

    private void PaLivrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaLivrosKeyReleased
        if(PaLivros.getSelectedRow()!=-1){

            CampoTit.setText(PaLivros.getValueAt(PaLivros.getSelectedRow(),1).toString());
            CampoIDL.setText(PaLivros.getValueAt(PaLivros.getSelectedRow(),0).toString());

        }
    }//GEN-LAST:event_PaLivrosKeyReleased

    private void CampoTituloPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTituloPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTituloPActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        readpesquisarLT(CampoTituloP.getText());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void CampoNomePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomePActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        readPesquisarForName(CampoNomeP.getText());
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void PaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaAlunosMouseClicked
        if(PaAlunos.getSelectedRow()!=-1){

            
            CampoNome.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),3).toString());
            CampoIDA.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),0).toString());
            

        }

    }//GEN-LAST:event_PaAlunosMouseClicked

    private void PaAlunosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaAlunosKeyReleased
        if(PaAlunos.getSelectedRow()!=-1){

            
            CampoNome.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),3).toString());
            CampoIDA.setText(PaAlunos.getValueAt(PaAlunos.getSelectedRow(),0).toString());

        }

    }//GEN-LAST:event_PaAlunosKeyReleased

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void CampoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoRActionPerformed

    private void CampoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEActionPerformed

    private void btnFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFRActionPerformed
        
        try{
        
        ReservaDAO rdao= new ReservaDAO();
        
        Aluno a = new Aluno();
        
        
        a.setId_a(Integer.parseInt(CampoIDA.getText()));
        a.setNome(CampoNome.getText());
        a.setDataE(CampoE.getText());
        a.setDataR(CampoR.getText());
        a.setPendente("Sim");
        
        Livros l = new Livros();
       
        LivroDAO ldao = new LivroDAO();
        l.setId_l(Integer.parseInt(CampoIDL.getText()));
        l.setTitulo(CampoTit.getText());
        if( "Sim".equals(l.getDisp())){
            JOptionPane.showMessageDialog(null, "Livro já esta emprestado");
        }
        else{
            l.setDisp("Não");
            rdao.createReserva(a, l);
            ldao.updateRL(l);
            readpesquisarLT(CampoTituloP.getText());
            
        }
       }
        catch (Exception ex){
           JOptionPane.showMessageDialog(null,"Erro ao salvar: " + ex);
       } 
       

        



    }//GEN-LAST:event_btnFRActionPerformed

    private void CampoIDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIDAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CampoE;
    private javax.swing.JTextField CampoIDA;
    private javax.swing.JTextField CampoIDL;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoNomeP;
    private javax.swing.JFormattedTextField CampoR;
    private javax.swing.JTextField CampoTit;
    private javax.swing.JTextField CampoTituloP;
    private javax.swing.JTable PaAlunos;
    private javax.swing.JTable PaLivros;
    private javax.swing.JButton btnFR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
