/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Aluno;
import model.bean.Livros;
import model.bean.Reserva;
import model.dao.AlunoDAO;
import model.dao.LivroDAO;
import model.dao.ReservaDAO;

/**
 *
 * @author user
 */
public class RemoverReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoverReserva
     */
    public RemoverReserva() {
        initComponents();
        readPesquisar();
        CampoAluno.setDocument(new JTextFieldLimit(30));
        
        
    }
     public void readPesquisar(){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaReservas.getModel();
        pesquisa.setNumRows(0);
        
        ReservaDAO rdao = new ReservaDAO();
        
        for(Reserva r:rdao.readRAID()){
            
            pesquisa.addRow(new Object[]{
            r.getId(),
            r.getId_a(),
            r.getNome(),
            r.getId_l(),
            r.getTituloo(),
            r.getDatarR(),
            r.getDataeE()     
        });
        
        
        
      }
    }
 
           
    
        
   
        public void readPesquisarForName(String nome){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaReservas.getModel();
        pesquisa.setNumRows(0);
        
       ReservaDAO rdao = new ReservaDAO();
        
        for(Reserva r:rdao.readRANID(nome)){
            
            pesquisa.addRow(new Object[]{
            r.getId(),
            r.getId_a(),
            r.getNome(),
            r.getId_l(),
            r.getTituloo(),
            r.getDatarR(),
            r.getDataeE()     
        });
            
        }
    }

   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPRR = new javax.swing.JToggleButton();
        Devolver = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PaReservas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        CampoIDL = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Remover Reserva");

        CampoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAlunoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Aluno");

        btnPRR.setText("Pesquisar");
        btnPRR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRRActionPerformed(evt);
            }
        });

        Devolver.setText("Devolver");
        Devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverActionPerformed(evt);
            }
        });

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setOpaque(false);

        PaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id da Reserva", "ID_A", "Aluno", "ID_L", "Titulo", "Data Retirada", "Data Entrega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaReservasMouseClicked(evt);
            }
        });
        PaReservas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaReservasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(PaReservas);
        PaReservas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel7.setText("ID do Titulo");

        CampoIDL.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Devolver)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnPRR, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CampoIDL)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPRR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoIDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(Devolver)
                .addGap(33, 33, 33))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoAlunoActionPerformed

    private void PaReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaReservasMouseClicked
        CampoIDL.setText(PaReservas.getValueAt(PaReservas.getSelectedRow(),3).toString());
    }//GEN-LAST:event_PaReservasMouseClicked

    private void btnPRRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRRActionPerformed
        readPesquisarForName(CampoAluno.getText());
        
        
    }//GEN-LAST:event_btnPRRActionPerformed

    private void DevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverActionPerformed
       try{
           if(PaReservas.getSelectedRow() != -1){
        
            Reserva r = new Reserva();
            ReservaDAO rdao = new ReservaDAO();
        
            r.setPendente("Não");
            
            r.setId((int) PaReservas.getValueAt(PaReservas.getSelectedRow(), 0));
        
        rdao.update(r);
        LivroDAO ldao = new LivroDAO();
        Livros l = new Livros();
        l.setId_l(Integer.parseInt(CampoIDL.getText()));
        l.setDisp("Sim");
        ldao.updateRL(l);
        readPesquisar();
              }
       }
       catch(NumberFormatException ex ){
           JOptionPane.showMessageDialog(null, "Erro ao Devolver Livro");
           
       }

    }//GEN-LAST:event_DevolverActionPerformed

    private void PaReservasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaReservasKeyReleased
    CampoIDL.setText(PaReservas.getValueAt(PaReservas.getSelectedRow(),0).toString());
    }//GEN-LAST:event_PaReservasKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoAluno;
    private javax.swing.JTextField CampoIDL;
    private javax.swing.JToggleButton Devolver;
    private javax.swing.JTable PaReservas;
    private javax.swing.JToggleButton btnPRR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
