/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConnectionFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Funcionario;
import model.dao.FuncionarioDAO;

/**
 *
 * @author user
 */
public class RemoverFunc extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoverAluno
     */
    public RemoverFunc() {
        initComponents();
        DefaultTableModel pesquisa = (DefaultTableModel) PaFunc.getModel();
        PaFunc.setRowSorter(new TableRowSorter(pesquisa));
        readPesquisar();
        CampoNome.setDocument(new JTextFieldLimit(30));
        CampoLoginM.setDocument(new JTextFieldLimit(7));
        CampoSenhaM.setDocument(new JTextFieldLimit(5));
    }
    public void readPesquisar(){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaFunc.getModel();
        pesquisa.setNumRows(0);
        
        FuncionarioDAO fdao = new FuncionarioDAO();
        
        for(Funcionario f:fdao.readFunc()){
            
            pesquisa.addRow(new Object[]{
            f.getId_f(),
            f.getNome(),
            f.getRg(),
            f.getNasc(),
            f.getEndereco(),
            f.getTel(),
            f.getLogin(),
            f.getSenha()
            
            
            //id_a, nome,sexo,ra, serie, turma, rg, nasc, End, tel
            
            });
        
            
        }
    }
           
    
        
   
        public void readPesquisarForName(String nome){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaFunc.getModel();
        pesquisa.setNumRows(0);
        
        FuncionarioDAO fdao = new FuncionarioDAO();
        
        for(Funcionario f:fdao.readFuncForName(nome)){
            
            pesquisa.addRow(new Object[]{
            f.getId_f(),
            f.getNome(),
            f.getRg(),
            f.getNasc(),
            f.getEndereco(),
            f.getTel(),
            f.getLogin(),
            f.getSenha()
            
            
            //id_a, nome,sexo,ra, serie, turma, rg, nasc, End, tel
            
            });
        
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        PaFunc = new javax.swing.JTable();
        CampoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPRA = new javax.swing.JToggleButton();
        btnRA = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        CampoSenhaM = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        CampoLoginM = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Remover Funcionario");
        setRequestFocusEnabled(false);

        PaFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "RG", "Nasc", "End", "Telefone", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaFuncMouseClicked(evt);
            }
        });
        PaFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaFuncKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(PaFunc);

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Aluno");

        btnPRA.setText("Pesquisar");
        btnPRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRAActionPerformed(evt);
            }
        });

        btnRA.setText("Remover");
        btnRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Senha Master:");

        CampoSenhaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenhaMActionPerformed(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Login Master:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPRA, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 389, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoLoginM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampoSenhaM, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnRA)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPRA))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CampoSenhaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CampoLoginM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRA))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void btnPRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRAActionPerformed
        readPesquisarForName(CampoNome.getText());
    }//GEN-LAST:event_btnPRAActionPerformed

    private void btnRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAActionPerformed
 if(PaFunc.getSelectedRow() != -1){
        
            FuncionarioDAO ffdao = new FuncionarioDAO();
            if(ffdao.checkLoginM(CampoLoginM.getText(), CampoSenhaM.getText())){
            Funcionario f = new Funcionario();
            FuncionarioDAO fadao = new FuncionarioDAO();

            f.setId_f((int)PaFunc.getValueAt(PaFunc.getSelectedRow(), 0));
            
            fadao.delete(f);
            
            readPesquisar();

}
 
            else{JOptionPane.showMessageDialog(null, "Login ou Senha Master Incorreta");
            }
 }
 
    }//GEN-LAST:event_btnRAActionPerformed

    private void PaFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaFuncMouseClicked
        if(PaFunc.getSelectedRow()!=-1){

           
        }

    }//GEN-LAST:event_PaFuncMouseClicked

    private void PaFuncKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaFuncKeyReleased
      
    }//GEN-LAST:event_PaFuncKeyReleased

    private void CampoSenhaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenhaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSenhaMActionPerformed
    
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoLoginM;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JPasswordField CampoSenhaM;
    private javax.swing.JTable PaFunc;
    private javax.swing.JToggleButton btnPRA;
    private javax.swing.JToggleButton btnRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
