/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.bean.Aluno;
import model.bean.Livros;
import model.dao.AlunoDAO;
import model.dao.LivroDAO;

/**
 *
 * @author user
 */
public class RemoverLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoverLivro
     */
    public RemoverLivro() {
        initComponents();
       readpesquisarL();
        CampoTitu.setDocument(new JTextFieldLimit(40));

        
        
    }
    
    
    public void readpesquisarL(){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaLivros.getModel();
        pesquisa.setNumRows(0);
        
        LivroDAO ldao = new LivroDAO();
        
        for(Livros l:ldao.readL()){
            
            pesquisa.addRow(new Object[]{
            l.getId_l(),
            l.getTitulo(),
            l.getAutor(),
            l.getGenero(),
            l.getDisp()
            
            
            
            
            
            });
        
            
        }
    }
      
    public void readpesquisarLT(String titulo){
        
        DefaultTableModel pesquisa = (DefaultTableModel) PaLivros.getModel();
        pesquisa.setNumRows(0);
        
        LivroDAO ldao = new LivroDAO();
        
        for(Livros l:ldao.readLT(titulo)){
            
            pesquisa.addRow(new Object[]{
            l.getId_l(),
            l.getTitulo(),
            l.getAutor(),
            l.getGenero(),
            l.getDisp()
            
            
            
            
            
            });
        
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRL = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PaLivros = new javax.swing.JTable();
        CampoTitu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPL = new javax.swing.JToggleButton();

        setClosable(true);
        setTitle("Remover Livro");

        btnRL.setText("Remover");
        btnRL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRLActionPerformed(evt);
            }
        });

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setOpaque(false);

        PaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Autor", "Genero", "Disponivel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaLivrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PaLivros);

        CampoTitu.setPreferredSize(null);
        CampoTitu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTituActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Livro:");
        jLabel1.setPreferredSize(null);

        btnPL.setText("Pesquisar");
        btnPL.setPreferredSize(null);
        btnPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRL)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CampoTitu, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnPL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoTitu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRL))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaLivrosMouseClicked

    }//GEN-LAST:event_PaLivrosMouseClicked

    private void CampoTituActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTituActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTituActionPerformed

    private void btnPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLActionPerformed

        readpesquisarLT(CampoTitu.getText());
    }//GEN-LAST:event_btnPLActionPerformed

    private void btnRLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRLActionPerformed
            Livros l = new Livros();
            LivroDAO ldao = new LivroDAO();

            l.setId_l((int)PaLivros.getValueAt(PaLivros.getSelectedRow(), 0));
            
            ldao.delete(l);
            
            readpesquisarL();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoTitu;
    private javax.swing.JTable PaLivros;
    private javax.swing.JToggleButton btnPL;
    private javax.swing.JToggleButton btnRL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
