/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        RemoveA = new javax.swing.JMenuItem();
        PesquisaA = new javax.swing.JMenuItem();
        EditaA = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AdicionaL = new javax.swing.JMenuItem();
        RemoveL = new javax.swing.JMenuItem();
        PesquisaL = new javax.swing.JMenuItem();
        EditaL = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Reserva = new javax.swing.JMenu();
        FazerR = new javax.swing.JMenuItem();
        RemoverR = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Info = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca 1.0");
        setPreferredSize(new java.awt.Dimension(1000, 720));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(299, 21));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 500));
        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page.png"))); // NOI18N
        jMenu1.setText("Arquivo");

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenu1.add(Sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1495775168_People.png"))); // NOI18N
        jMenu2.setText("Alunos");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_add.png"))); // NOI18N
        jMenuItem2.setText("Adicionar Aluno");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        RemoveA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_delete.png"))); // NOI18N
        RemoveA.setText("Remover Aluno");
        RemoveA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAActionPerformed(evt);
            }
        });
        jMenu2.add(RemoveA);

        PesquisaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        PesquisaA.setText("Pesquisar Alunos");
        PesquisaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaAActionPerformed(evt);
            }
        });
        jMenu2.add(PesquisaA);

        EditaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        EditaA.setText("Editar Aluno");
        EditaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditaAActionPerformed(evt);
            }
        });
        jMenu2.add(EditaA);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HISTO__LIVROS.png"))); // NOI18N
        jMenuItem3.setText("Historico de Livros");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1495775180_Notes.png"))); // NOI18N
        jMenu4.setText("Livros");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        AdicionaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Adicionar Livro.png"))); // NOI18N
        AdicionaL.setText("Adicionar Livro");
        AdicionaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionaLActionPerformed(evt);
            }
        });
        jMenu4.add(AdicionaL);

        RemoveL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remover Livro.png"))); // NOI18N
        RemoveL.setText("Remover Livro");
        RemoveL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLActionPerformed(evt);
            }
        });
        jMenu4.add(RemoveL);

        PesquisaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesq Livro.png"))); // NOI18N
        PesquisaL.setText("Pesquisar Livros");
        PesquisaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaLActionPerformed(evt);
            }
        });
        jMenu4.add(PesquisaL);

        EditaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar Livro (2).png"))); // NOI18N
        EditaL.setText("Editar Livro");
        EditaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditaLActionPerformed(evt);
            }
        });
        jMenu4.add(EditaL);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/histAlunos.png"))); // NOI18N
        jMenuItem8.setText("Historico de Alunos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        Reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1495775218_New.png"))); // NOI18N
        Reserva.setText("Reserva");
        Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaActionPerformed(evt);
            }
        });

        FazerR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1495774293_Green_tag.png"))); // NOI18N
        FazerR.setText("Emprestar Livro");
        FazerR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FazerRActionPerformed(evt);
            }
        });
        Reserva.add(FazerR);

        RemoverR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1495774258_Yellow_tag.png"))); // NOI18N
        RemoverR.setText("Devolver Reserva");
        RemoverR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverRActionPerformed(evt);
            }
        });
        Reserva.add(RemoverR);

        jMenuBar1.add(Reserva);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1495775186_Boss.png"))); // NOI18N
        jMenu5.setText("Funcionario");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add func.png"))); // NOI18N
        jMenuItem4.setText("Adicionar Funcionario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delet Func.png"))); // NOI18N
        jMenuItem6.setText("Deletar Funcionario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pesq Func.png"))); // NOI18N
        jMenuItem7.setText("Pesquisar Funcionario");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit Func.png"))); // NOI18N
        jMenuItem5.setText("Editar Funcionario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        Info.setText("Informacoes");

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jMenuItem13.setText("Informacoes");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        Info.add(jMenuItem13);

        jMenuBar1.add(Info);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AdicionarAluno adAluno = new AdicionarAluno();
        jDesktopPane1.add(adAluno);
        adAluno.setVisible(true);
         
        
        
        
        

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void RemoveAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAActionPerformed
         RemoverAluno rAluno = new RemoverAluno();
        jDesktopPane1.add(rAluno);
        rAluno.setVisible(true);
    }//GEN-LAST:event_RemoveAActionPerformed

    private void AdicionaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionaLActionPerformed
        AdicionarLivro aLivro = new AdicionarLivro();
        jDesktopPane1.add(aLivro);
        aLivro.setVisible(true);
    }//GEN-LAST:event_AdicionaLActionPerformed

    private void RemoveLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveLActionPerformed
        RemoverLivro rLivro = new RemoverLivro();
        jDesktopPane1.add(rLivro);
        rLivro.setVisible(true);
    }//GEN-LAST:event_RemoveLActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_SairActionPerformed

    private void PesquisaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaAActionPerformed
        PesquisarAluno pAluno = new PesquisarAluno();
        jDesktopPane1.add(pAluno);
        pAluno.setVisible(true);
    }//GEN-LAST:event_PesquisaAActionPerformed

    private void EditaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditaAActionPerformed
        EditarAluno eAluno= new EditarAluno();
        jDesktopPane1.add(eAluno);
        eAluno.setVisible(true);
        
    }//GEN-LAST:event_EditaAActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        RemoverLivro rLivro = new RemoverLivro();
        jDesktopPane1.add(rLivro);
        rLivro.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void PesquisaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaLActionPerformed
       PesquisarLivro pLivro = new PesquisarLivro();
        jDesktopPane1.add(pLivro);
        pLivro.setVisible(true);
    }//GEN-LAST:event_PesquisaLActionPerformed

    private void EditaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditaLActionPerformed
        EditarLivro eLivro= new EditarLivro();
        jDesktopPane1.add(eLivro);
        eLivro.setVisible(true);
        
    }//GEN-LAST:event_EditaLActionPerformed

    private void ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaActionPerformed
        FazerReserva fReserva = new FazerReserva();
        jDesktopPane1.add(fReserva);
        fReserva.setVisible(true);
        
    }//GEN-LAST:event_ReservaActionPerformed

    private void RemoverRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverRActionPerformed
        RemoverReserva rReserva= new RemoverReserva();
        jDesktopPane1.add(rReserva);
        rReserva.setVisible(true);

    }//GEN-LAST:event_RemoverRActionPerformed

    private void FazerRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FazerRActionPerformed
        FazerReserva fReserva= new FazerReserva();
        jDesktopPane1.add(fReserva);
        fReserva.setVisible(true);
    }//GEN-LAST:event_FazerRActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
            Informacoes info = new Informacoes();
            jDesktopPane1.add(info);
            info.setVisible(true);


    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AdicionarFuncionario aFunc = new AdicionarFuncionario();
        jDesktopPane1.add(aFunc);
        aFunc.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        EditarFunc ef = new EditarFunc();
        jDesktopPane1.add(ef);
        ef.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        PesquisarFunc pf = new PesquisarFunc();
        jDesktopPane1.add(pf);
        pf.setVisible(true);


    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        RemoverFunc rf = new RemoverFunc();
        jDesktopPane1.add(rf);
        rf.setVisible(true);
        


    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jDesktopPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            jPopupMenu1.show(this, evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_jDesktopPane1MouseReleased

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
               Historico_Livros hl = new Historico_Livros();
               jDesktopPane1.add(hl);
               hl.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
                Historico_Alunos ha = new Historico_Alunos();
                jDesktopPane1.add(ha);
                ha.setVisible(true);
                        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdicionaL;
    private javax.swing.JMenuItem EditaA;
    private javax.swing.JMenuItem EditaL;
    private javax.swing.JMenuItem FazerR;
    private javax.swing.JMenu Info;
    private javax.swing.JMenuItem PesquisaA;
    private javax.swing.JMenuItem PesquisaL;
    private javax.swing.JMenuItem RemoveA;
    private javax.swing.JMenuItem RemoveL;
    private javax.swing.JMenuItem RemoverR;
    private javax.swing.JMenu Reserva;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
